version: '3.8'

services:
  api:
    image: php:7.4-apache
    container_name: codeigniter3
    ports:
      - '3035:80'
    volumes:
      - ./src:/var/www/html
    networks:
      - shared_network
      - internal_network
    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql &&
             a2enmod rewrite &&
             apache2-foreground"

  db:
    image: mysql:9
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rediscasedb
    volumes:
      - ../../mysql/mysql-init:/docker-entrypoint-initdb.d
      - ../../mysql/mysql-logs:/var/log/mysql
    networks:
      - internal_network
    command: --general-log=1 --general-log-file=/var/log/mysql/general.log

  redis:
    image: redis:7.2.1
    ports:
      - 6380:6379
    restart: always
    volumes:
      - ../../redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    networks:
      - internal_network

networks:
  shared_network:
    driver: bridge
  internal_network:
    internal: true
